name: Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-and-jest-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node v19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Setup yarn
        uses: borales/actions-yarn@v3.0.0
      - name: Install Dependencies 
        run: |
          sudo yarn
      - name: Check syntax 
        run: |
          sudo yarn lint
      - name: Tests with jest
        run: |
          sudo yarn test