name: Test Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-and-jest-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Check syntax 
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Tests with jest
        uses: borales/actions-yarn@v4
        with:
          cmd: test